### ISSUE TITLE
Organizing rendering/inputs

### ISSUE THREAD

**Issue by chanko08** [chanko08/Geometry#32]
In an MVC designed application, it makes sense that the inputs (keypress, mouse clicks) are sent from the renderer (View), interpretted by the controller, and then sent to the model.

Currently we are mixing our View (CameraSystem?, renderers arguably) and controllers (InputSystem) a tiny bit, and it may make sense to solidify their coupling in a way we can use somewhere else.

**Comment by uncleverone** [comment]
I believe we have this done now.
